In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv('16_cardataset.csv')

In [3]:
print(dataset.shape)
print(dataset.head(5))

(205, 26)
   car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two
1       2          3       alfa-romero stelvio      gas        std        two
2       3          1  alfa-romero Quadrifoglio      gas        std        two
3       4          2               audi 100 ls      gas        std       four
4       5          2                audi 100ls      gas        std       four

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130
1  convertible        rwd          front       88.6  ...         130
2    hatchback        rwd          front       94.5  ...         152
3        sedan        fwd          front       99.8  ...         109
4        sedan        4wd          front       99.4  ...         136

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21
1        mpfi       3.47    2.68              9.0        111     5000      21
2        mpfi       2.68    3.47              9.0        154     5000      19
3        mpfi       3.19    3.40             10.0        102     5500      24
4        mpfi       3.19    3.40              8.0        115     5500      18

   highwaympg    price
0          27  13495.0
1          27  16500.0
2          26  16500.0
3          30  13950.0
4          22  17450.0

[5 rows x 26 columns]

In [4]:
dataset=dataset.drop(['car_ID'],axis=1)

In [5]:
dataset.head(5)

,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [6]:
'''splitting dataset into x and y'''
xdata=dataset.drop('price',axis='columns')
numericalCols=xdata.select_dtypes(exclude=['object']).columns #removes all the categorical data
x=xdata[numericalCols]
x

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27
1,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27
2,1,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,154,5000,19,26
3,2,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,102,5500,24,30
4,2,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,115,5500,18,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,109.1,188.8,68.9,55.5,2952,141,3.78,3.15,9.5,114,5400,23,28
201,-1,109.1,188.8,68.8,55.5,3049,141,3.78,3.15,8.7,160,5300,19,25
202,-1,109.1,188.8,68.9,55.5,3012,173,3.58,2.87,8.8,134,5500,18,23
203,-1,109.1,188.8,68.9,55.5,3217,145,3.01,3.40,23.0,106,4800,26,27
204,-1,109.1,188.8,68.9,55.5,3062,141,3.78,3.15,9.5,114,5400,19,25

In [7]:
y=dataset['price'].values
y

array([13495.   , 16500.   , 16500.   , 13950.   , 17450.   , 15250.   ,
       17710.   , 18920.   , 23875.   , 17859.167, 16430.   , 16925.   ,
       20970.   , 21105.   , 24565.   , 30760.   , 41315.   , 36880.   ,
        5151.   ,  6295.   ,  6575.   ,  5572.   ,  6377.   ,  7957.   ,
        6229.   ,  6692.   ,  7609.   ,  8558.   ,  8921.   , 12964.   ,
        6479.   ,  6855.   ,  5399.   ,  6529.   ,  7129.   ,  7295.   ,
        7295.   ,  7895.   ,  9095.   ,  8845.   , 10295.   , 12945.   ,
       10345.   ,  6785.   ,  8916.5  ,  8916.5  , 11048.   , 32250.   ,
       35550.   , 36000.   ,  5195.   ,  6095.   ,  6795.   ,  6695.   ,
        7395.   , 10945.   , 11845.   , 13645.   , 15645.   ,  8845.   ,
        8495.   , 10595.   , 10245.   , 10795.   , 11245.   , 18280.   ,
       18344.   , 25552.   , 28248.   , 28176.   , 31600.   , 34184.   ,
       35056.   , 40960.   , 45400.   , 16503.   ,  5389.   ,  6189.   ,
        6669.   ,  7689.   ,  9959.   ,  8499.   , 12629.   , 14869.   ,
       14489.   ,  6989.   ,  8189.   ,  9279.   ,  9279.   ,  5499.   ,
        7099.   ,  6649.   ,  6849.   ,  7349.   ,  7299.   ,  7799.   ,
        7499.   ,  7999.   ,  8249.   ,  8949.   ,  9549.   , 13499.   ,
       14399.   , 13499.   , 17199.   , 19699.   , 18399.   , 11900.   ,
       13200.   , 12440.   , 13860.   , 15580.   , 16900.   , 16695.   ,
       17075.   , 16630.   , 17950.   , 18150.   ,  5572.   ,  7957.   ,
        6229.   ,  6692.   ,  7609.   ,  8921.   , 12764.   , 22018.   ,
       32528.   , 34028.   , 37028.   , 31400.5  ,  9295.   ,  9895.   ,
       11850.   , 12170.   , 15040.   , 15510.   , 18150.   , 18620.   ,
        5118.   ,  7053.   ,  7603.   ,  7126.   ,  7775.   ,  9960.   ,
        9233.   , 11259.   ,  7463.   , 10198.   ,  8013.   , 11694.   ,
        5348.   ,  6338.   ,  6488.   ,  6918.   ,  7898.   ,  8778.   ,
        6938.   ,  7198.   ,  7898.   ,  7788.   ,  7738.   ,  8358.   ,
        9258.   ,  8058.   ,  8238.   ,  9298.   ,  9538.   ,  8449.   ,
        9639.   ,  9989.   , 11199.   , 11549.   , 17669.   ,  8948.   ,
       10698.   ,  9988.   , 10898.   , 11248.   , 16558.   , 15998.   ,
       15690.   , 15750.   ,  7775.   ,  7975.   ,  7995.   ,  8195.   ,
        8495.   ,  9495.   ,  9995.   , 11595.   ,  9980.   , 13295.   ,
       13845.   , 12290.   , 12940.   , 13415.   , 15985.   , 16515.   ,
       18420.   , 18950.   , 16845.   , 19045.   , 21485.   , 22470.   ,
       22625.   ])

In [8]:
'''FEATURE SCALING of indep var'''
from sklearn.preprocessing import scale
cols=x.columns
x=pd.DataFrame(scale(x))
x.columns=cols
x

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,1.743470,-1.690772,-0.426521,-0.844782,-2.020417,-0.014566,0.074449,0.519071,-1.839377,-0.288349,0.174483,-0.262960,-0.646553,-0.546059
1,1.743470,-1.690772,-0.426521,-0.844782,-2.020417,-0.014566,0.074449,0.519071,-1.839377,-0.288349,0.174483,-0.262960,-0.646553,-0.546059
2,0.133509,-0.708596,-0.231513,-0.190566,-0.543527,0.514882,0.604046,-2.404880,0.685946,-0.288349,1.264536,-0.262960,-0.953012,-0.691627
3,0.938490,0.173698,0.207256,0.136542,0.235942,-0.420797,-0.431076,-0.517266,0.462183,-0.035973,-0.053668,0.787855,-0.186865,-0.109354
4,0.938490,0.107110,0.207256,0.230001,0.235942,0.516807,0.218885,-0.517266,0.462183,-0.540725,0.275883,0.787855,-1.106241,-1.273900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1.476452,1.721873,1.198549,1.398245,0.728239,0.763241,0.339248,1.666445,-0.336970,-0.162161,0.250533,0.577692,-0.340094,-0.400490
201,-1.476452,1.721873,1.198549,1.351515,0.728239,0.949992,0.339248,1.666445,-0.336970,-0.364062,1.416637,0.367529,-0.953012,-0.837195
202,-1.476452,1.721873,1.198549,1.398245,0.728239,0.878757,1.109571,0.926204,-1.232021,-0.338824,0.757535,0.787855,-1.106241,-1.128332
203,-1.476452,1.721873,1.198549,1.398245,0.728239,1.273437,0.435538,-1.183483,0.462183,3.244916,0.047732,-0.683286,0.119594,-0.546059
204,-1.476452,1.721873,1.198549,1.398245,0.728239,0.975021,0.339248,1.666445,-0.336970,-0.162161,0.250533,0.577692,-0.953012,-0.837195

In [9]:
'''train test split'''
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [10]:
'''Training using Random Forest'''
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(max_depth=9, random_state=0)
model.fit(x_train,y_train)

RandomForestRegressor(max_depth=9, random_state=0)

In [11]:
'''Evaluating graph'''
y_pred=model.predict(x_test)
from sklearn.metrics import r2_score
r2score=r2_score(y_test,y_pred)
print('R2Score: ',r2score*100)

R2Score:  91.0175704425004

In [12]:
from sklearn.metrics import mean_squared_error
print(f'Mean Squared Error: {np.sqrt(mean_squared_error(y_test,y_pred))}')

Mean Squared Error: 2588.053408073074

In [13]:
x_values=[[3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,111,5000,21,27]]
x_values=pd.DataFrame(x_values)
result=model.predict(x_values)
print("The price of the given car is: Rs {0}".format(result[0]))

The price of the given car is: Rs 33400.44